sudo: required
#language: generic  
services:
  - docker

before_install:
  - docker build -t leoncen0/learning_docker -f Dockerfile.dev .

script:
  - docker run leoncen0/learning_docker npm run test -- --coverage 